
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-RecommendationRequest-backend","number":70,"title":"Copied backend files from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/70"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-MenuItemReview-fixtures","number":69,"title":"AJ -- fixture created for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/69"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-MenuItemReview-CopyBackend","number":68,"title":"AJ -- MenuItemReview Backend copied from team02","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/68"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"LG-HR-table","number":67,"title":"Lg hr table","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/67"},{"author":{"id":"MDQ6VXNlcjkxMjg3MTQw","is_bot":false,"login":"jtanggy","name":"Likhit Gudisay"},"headRefName":"LG-HR-form","number":66,"title":"Lg hr form","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/66"}]
