
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBdHZtA","is_bot":false,"login":"alexanderthomasucsb","name":""},"headRefName":"at-UCSBOrganization-indexPageHelp","number":131,"title":"At ucsb organization index page help","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/131"}]
