
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-MenuItemReviews-CreatePage","number":82,"title":"AJ -- create page for MenuItemReview plus tests and stories","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/82"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-MenuItemReview-Placeholders","number":81,"title":"AJ -- MenuItemReview copied placeholders and added to navbar/app","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/81"},{"author":{"id":"U_kgDOCU6okQ","is_bot":false,"login":"chrisriney4","name":""},"headRefName":"Chris-Articles","number":80,"title":"cr - #55","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/80"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-MenuItemReview-TableComponent","number":79,"title":"AJ -- created table component for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/79"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-MenuItemReview-Component1","number":78,"title":"AJ -- create form component and tests for MenuItemReviews","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/78"},{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"Tyler-FixturesPlaceholdersComponents","number":76,"title":"Tyler fixtures placeholders components","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/76"},{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-MenuItemReview-fixtures","number":69,"title":"AJ -- fixture created for MenuItemReview","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/69"}]
