
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-w24/team03-w24-4pm-1
owner: ucsb-cs156-w24
repo_name: team03-w24-4pm-1
pull_requests: [{"author":{"id":"U_kgDOBXzOFw","is_bot":false,"login":"jinanthony","name":""},"headRefName":"AJ-fixMIR","number":119,"title":"Update MenuItemReviewCreatePage.js","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/119"},{"author":{"id":"MDQ6VXNlcjgzODAwODc1","is_bot":false,"login":"TianyiYang-Tyler","name":""},"headRefName":"pr/112","number":118,"title":"Pr/112","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/118"},{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-RecommendationRequest-placeholders-new","number":114,"title":"Arnav recommendation request placeholders new","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/114"},{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-RecommendationRequest-indexpage","number":108,"title":"Arnav recommendation request indexpage","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/108"},{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-RecommendationRequest-createpage","number":107,"title":"Arnav recommendation request createpage","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/107"},{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-RecommendationRequest-placeholders","number":106,"title":"Arnav recommendation request placeholders","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/106"},{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-RecommendationRequest-table","number":105,"title":"Arnav recommendation request table","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/105"},{"author":{"id":"U_kgDOBbtXkA","is_bot":false,"login":"aarnavkumar","name":""},"headRefName":"Arnav-RecommendationRequest-form","number":90,"title":"Initial commit","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/90"},{"author":{"id":"U_kgDOBdHZtA","is_bot":false,"login":"alexanderthomasucsb","name":""},"headRefName":"at-UCSBOrganization-fixtures","number":87,"title":"At ucsb organization fixtures","url":"https://github.com/ucsb-cs156-w24/team03-w24-4pm-1/pull/87"}]
